import { about, personalInfo } from "@/data/portfolio";

const siteUrl = "https://nikunj.codenex.dev";
export const ogLocale = "en_IN";

export const siteConfig = {
  siteUrl,
  homeUrl: `${siteUrl}/`,
  resumeUrl: `${siteUrl}${personalInfo.resumeUrl}`,
  updatedAt: "2026-04-08T00:00:00.000Z",
  siteName: "Nikunj Khitha Portfolio",
  title: `${personalInfo.name} — Full-Stack GenAI Engineer`,
  description: personalInfo.tagline,
  author: personalInfo.name,
  creator: personalInfo.name,
  email: personalInfo.email,
  github: personalInfo.github,
  linkedin: personalInfo.linkedin,
  locale: "en-IN",
  ogLocale,
  ogImage: "/og-image.svg",
  keywords: [
    "Nikunj Khitha",
    "Full-Stack Engineer",
    "Backend Engineer",
    "AI Engineer",
    "Platform Engineer",
    "Software Engineer",
    "GenAI Products",
    "Backend Systems",
    "API Design",
    "Distributed Systems",
    "DevOps",
    "Platform Engineering",
    "CI/CD",
    "Observability",
    "GraphRAG",
    "LightRAG",
    "Multi-Agent Systems",
    "Agentic AI",
    "AI Automation",
    "TypeScript",
    "Node.js",
    "Go",
    "Gin",
    "MCP",
    "LangChain",
    "LangGraph",
    "FastAPI",
    "Spring Boot",
    "AI Infrastructure",
    "AI Gateways",
    "RAG",
    "Full-Stack Development",
  ],
  geo: {
    region: "IN-HR",
    placename: "Gurugram, Haryana, India",
    latitude: 28.4595,
    longitude: 77.0266,
    position: "28.4595;77.0266",
    icbm: "28.4595, 77.0266",
  },
  sameAs: [personalInfo.github, personalInfo.linkedin],
  aboutSummary: about.summary,
} as const;

export const canonicalPages = [siteConfig.homeUrl] as const;
